### ISSUE TITLE
composing app status is updating all the time

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#773] opened 2020-07-17 02:33 UTC
**Describe the bug**
The samle app bookinfo is deployed successfully, but the status is updating all the time.
<img width="1034" alt="Screen Shot 2020-07-17 at 10 30 55 AM" src="https://user-images.githubusercontent.com/28859385/87742199-d0701c80-c818-11ea-984f-bff6ddbe78b2.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev

**Environment**
allinone

**Comment by leoendless** [comment] 2020-07-17 02:36
Duplicate of #https://github.com/kubesphere/kubesphere/issues/2351

**Closed by leoendless** 2020-07-17 02:36 UTC
Labels: area/console, kind/bug
