### ISSUE TITLE
Unexpected error when open an empty ingress list page

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#617] opened 2020-07-06 03:35 UTC
![image](https://user-images.githubusercontent.com/22350668/86553259-ce869d80-bf7c-11ea-9116-1fa40647b92d.png)

**Comment by leoendless** [comment] 2020-07-13 03:58
Duplicate of #https://github.com/kubesphere/kubesphere/issues/2356

**Closed by leoendless** 2020-07-13 03:58 UTC
Labels: kind/bug
