### ISSUE TITLE
PR msg broken link

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#846] opened 2020-07-21 09:07 UTC
When people pulls a request, it shows the following message, but the contribution guide link is broken
![Screen Shot 2020-07-21 at 5 06 12 PM](https://user-images.githubusercontent.com/28859385/88035368-9f734d00-cb74-11ea-93c3-51ae8c71f63d.png)

**Comment by leoendless** [comment] 2020-07-21 09:42
Duplicate of #845

**Closed by leoendless** 2020-07-21 09:42 UTC
Labels: area/documentation, priority/low
