### ISSUE TITLE
rerun job error

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#733] opened 2020-07-13 06:01 UTC
**Describe the bug**
Run a job successfully, then try to re-run the job, got error msg.

<img width="1246" alt="Screen Shot 2020-07-13 at 1 58 54 PM" src="https://user-images.githubusercontent.com/28859385/87275625-1b381e80-c511-11ea-95b7-668360b61345.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev

**Environment**
allinone, minimal installation

**Expected behavior**
Can re-run the job successfully.

**Comment by leoendless** [comment] 2020-07-13 06:02
Duplicate of #554

**Closed by leoendless** 2020-07-13 06:02 UTC
Labels: area/deploy, kind/bug
