### ISSUE TITLE
cannot modify user password

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/console#638] opened 2020-07-06 12:24 UTC
![image](https://user-images.githubusercontent.com/3678855/86592804-b50a4380-bfc6-11ea-9673-d4365889b3c2.png)

**Comment by leoendless** [comment] 2020-07-06 12:41
Duplicate of https://github.com/kubesphere/kubesphere/issues/2242

**Closed** 2020-07-06 12:42 UTC
Labels: kind/bug
